### ISSUE TITLE
扔了一百个数据进去之后, 效果有点酸爽

### ISSUE THREAD

**Issue by liguobao** [wZi/ReactRouletteSlot#3]
建议支持自定义行列个数以及默认填充空白位置.

**Comment by wZi** [comment]
row | 每行个数 是支持的. 
左右两侧的只支持 1 个.

**Comment by liguobao** [comment]
这样也不太好用...

**Comment by wZi** [comment]
那你是想实现什么样的效果?
A A A A A    <-row
A           A
A A A A A

**Comment by liguobao** [comment]
支持配置 n, 生成 n *n 的 格子, 然后自定义中奖抽奖的格子是几个小格子的合并

**Comment by wZi** [comment]
我还是搞不懂, 你可以像我上面那样画一个示意图吗?
